version: '2'
services:

  default:
    build: .

  redis:
    image: redis:latest
    volumes:
      - redis:/var/lib/redis/data

  db:
    image: postgres:9.5.4
    volumes:
      - postgres:/var/lib/postgres

  web:
    extends:
      service: default
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/prompt
    depends_on:
      - db
      - redis
      - sidekiq

  sidekiq:
    extends:
      service: default
    volumes:
      - .:/prompt
    links:
      - db
      - redis
    command: bundle exec sidekiq

volumes:
  postgres:
  redis:
