default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USER'] %>
  min_messages: notice
  host: db

development:
  <<: *default
  database: prompt_development

test:
  <<: *default
  database: prompt_test
